# Generated by Django 4.2.1 on 2023-11-15 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabric', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Название ресурса')),
                ('status', models.IntegerField(choices=[(1, 'Другое'), (2, 'Запрашиваемый'), (3, 'Наличный'), (4, 'В процессе изготовления')])),
                ('fabric_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_made', to='fabric.fabric', verbose_name='Фабрика-изготовитель')),
            ],
        ),
    ]
